name: CICD for Major Assessment on Refactoring

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run linter
      run: flake8 refactored_analysis.py --ignore=E501,W503
    - name: Format with black
      run: black refactored_analysis.py
    - name: Run tests
      run: pytest --cov=test_analysis.py